[package]
name = "vtable_bench"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
edition = "2018"

[dependencies]
getopts = "0.2"
lazy_static = "1.2"
rand = "0.6"
statistical = "1.0"
